disable pypy builds
they build OK but result in errors like the following when you try to import the lcm module:

      import lcm
  ../venv-test-arm64/lib/pypy3.8/site-packages/lcm/__init__.py:23: in <module>
      from lcm import _lcm
  E   ImportError: cannot import name '_lcm' from partially initialized module 'lcm' (most likely due to a circular import)